# Generated by Django 5.0.3 on 2024-04-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
